# Site settings
title: 정민
description: Java, Node JS 백엔드 엔지니어
baseurl: "https://overult01.github.io/" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 정민
user_description: 백엔드 개발자가 되기 위해 끊임없는 성장을 추구하고 있습니다.
user_title: Backend Engineer
email: overult01@gmail.com
blog: https://structuring.tistory.com/
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
